# Generated by Django 4.1 on 2023-06-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_auto_20210310_0021"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrydata",
            options={"verbose_name_plural": "國家 人口 Data"},
        ),
    ]
