# Generated by Django 4.1 on 2023-06-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_city_alter_countrydata_id_county"),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrydata",
            name="country",
            field=models.CharField(max_length=255),
        ),
    ]
